name: Build and Push  # Workflow name

on:   # Event - Defines when this workflow should trigger
  push:
    branches:
      - master
    paths:
      - day1/**  # Runs only if files inside 'day1/' change
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:  
  build:  # First job - "build"
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:  # Steps define actions performed in the job      
      - name: Checkout code  # Step 1 - Clone repository into the runner
        uses: actions/checkout@v2  

      - name: Configure AWS credentials  # Step 2 - Set up AWS authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR  # Step 3 - Authenticate Docker with AWS ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 767398153139.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Push Docker image  # Step 4 - Build and push image to ECR  
        run: |
          docker build -t 767398153139.dkr.ecr.ap-south-1.amazonaws.com/devops-bootcamp:daytwo .
          docker push 767398153139.dkr.ecr.ap-south-1.amazonaws.com/devops-bootcamp:daytwo
